### ISSUE TITLE
Using a new UniqueKey with every build 

### ISSUE THREAD

**Issue by derolf** [sarcastic-verma/dialog_switcher#1]
https://github.com/sarcastic-verma/dialog_switcher/blob/5dff7bbb31f01e746fe3b02317a54348488a519b/lib/dialog_switcher.dart#L153

This will lead to constant rebuilds of the child.

**Comment by sarcastic-verma** [comment]
Oh, thanks for bringing it to my notice. Will fix it ASAP.

**Comment by sarcastic-verma** [comment]
The fix is live ✨

**Comment by derolf** [comment]
The fix is wrong. You should not attach mutable state to a Widget, but to State.

**Comment by sarcastic-verma** [comment]
Can you make a PR for the same, so I can merge it?

**Comment by sarcastic-verma** [comment]
Hi, I have fixed the issue.
